---
- hosts: localhost
  become: true 
  tasks:
    - name: Install tools
      apt:
        name: '{{ item }}'
        state: present
      loop: 
        - python3
        - openssh-server 
        - git
    